// <auto-generated />
using System;
using FindlyDAL.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindlyDAL.Migrations
{
    [DbContext(typeof(FindlyDbContext))]
    [Migration("20251109215011_shopHasData")]
    partial class shopHasData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FindlyDAL.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN_13")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoverId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublisherId");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("FindlyDAL.Entities.Cover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cover");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ShopId");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("FindlyDAL.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceNodePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0adccd8c-8b5c-4d7a-8022-07a64f6a5475"),
                            Name = "Yakaboo.ua",
                            ParserType = "JsonLd",
                            PriceNodePath = "//script[@data-vmid=\"ProductJsonLd\"]",
                            ShopImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("c3395966-f529-49a7-a43e-d0d6e6d19218"),
                            Name = "balka-book.com",
                            ParserType = "JsonLd",
                            PriceNodePath = "//script[@type='application/ld+json']",
                            ShopImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("475d94f1-6a93-4856-ab54-f6bcd8b1968e"),
                            Name = "book24.ua",
                            ParserType = "Node",
                            PriceNodePath = "//div[@class='product-main']//span[@class='price_value']",
                            ShopImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("8bebdcbf-e371-4506-aff1-6b7e424df6fe"),
                            Name = "ksd.ua",
                            ParserType = "JsonLd",
                            PriceNodePath = "//script[@type='application/ld+json']",
                            ShopImageUrl = ""
                        });
                });

            modelBuilder.Entity("FindlyDAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FindlyDAL.Entities.UserLikedOffers", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PriceToNotify")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId", "OfferId");

                    b.HasIndex("OfferId");

                    b.ToTable("UserLikedOffers");
                });

            modelBuilder.Entity("authors_books", b =>
                {
                    b.Property<Guid>("authorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("bookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("authorId", "bookId");

                    b.HasIndex("bookId");

                    b.ToTable("authors_books");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Book", b =>
                {
                    b.HasOne("FindlyDAL.Entities.Cover", "Cover")
                        .WithMany("Books")
                        .HasForeignKey("CoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cover");

                    b.Navigation("Language");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Offer", b =>
                {
                    b.HasOne("FindlyDAL.Entities.Book", "Book")
                        .WithMany("Offers")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.Shop", "Shop")
                        .WithMany("Offers")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FindlyDAL.Entities.UserLikedOffers", b =>
                {
                    b.HasOne("FindlyDAL.Entities.Offer", "Offer")
                        .WithMany("LikedOffers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.User", "User")
                        .WithMany("LikedOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("authors_books", b =>
                {
                    b.HasOne("FindlyDAL.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("authorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FindlyDAL.Entities.Book", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Cover", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Offer", b =>
                {
                    b.Navigation("LikedOffers");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Shop", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("FindlyDAL.Entities.User", b =>
                {
                    b.Navigation("LikedOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
