// <auto-generated />
using System;
using FindlyDAL.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindlyDAL.Migrations
{
    [DbContext(typeof(FindlyDbContext))]
    [Migration("20251112215822_seed data")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FindlyDAL.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a259a396-b950-4d63-8ce9-8b83fa187a8e"),
                            Name = "Джордж Орвелл"
                        },
                        new
                        {
                            Id = new Guid("391d1568-480f-4164-a10f-2c38a7391858"),
                            Name = "Френк Герберт"
                        },
                        new
                        {
                            Id = new Guid("7c69abe6-7604-4804-8d45-d5bdde4410d9"),
                            Name = "Анджей Сапковський"
                        });
                });

            modelBuilder.Entity("FindlyDAL.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN_13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoverId");

                    b.HasIndex("PublisherId");

                    b.ToTable("books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("26e5c51c-37e3-4c38-8e3e-41332eeaea73"),
                            CoverId = new Guid("a9819fd8-65c7-4925-af38-a29c030280f6"),
                            ISBN_13 = "978-966-993-391-1",
                            PublisherId = new Guid("42e470a1-702a-4994-a7f9-0b7283cc41d6"),
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("00461873-724c-49bf-adde-fe204bce4466"),
                            CoverId = new Guid("2a9dbeec-0c49-41e5-b947-dcd3d5b6f717"),
                            ISBN_13 = "978-617-7910-08-3",
                            PublisherId = new Guid("0a20441e-d50a-4da4-b560-a91c4aa69080"),
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("11226951-89aa-4611-9346-11b9aba3d52d"),
                            CoverId = new Guid("a9819fd8-65c7-4925-af38-a29c030280f6"),
                            ISBN_13 = "978-617-12-7689-5",
                            PublisherId = new Guid("42e470a1-702a-4994-a7f9-0b7283cc41d6"),
                            Title = "Дюна"
                        },
                        new
                        {
                            Id = new Guid("c043abf2-91e1-4e68-82bd-8d55c88d7457"),
                            CoverId = new Guid("a9819fd8-65c7-4925-af38-a29c030280f6"),
                            ISBN_13 = "978-617-12-8351-0",
                            PublisherId = new Guid("42e470a1-702a-4994-a7f9-0b7283cc41d6"),
                            Title = "Відьмак. Останнє бажання. Книга 1"
                        });
                });

            modelBuilder.Entity("FindlyDAL.Entities.Cover", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cover");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9819fd8-65c7-4925-af38-a29c030280f6"),
                            Name = "Тверда"
                        },
                        new
                        {
                            Id = new Guid("2a9dbeec-0c49-41e5-b947-dcd3d5b6f717"),
                            Name = "М'яка"
                        });
                });

            modelBuilder.Entity("FindlyDAL.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ShopId");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("FindlyDAL.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42e470a1-702a-4994-a7f9-0b7283cc41d6"),
                            Title = "Видавництво Жупанського"
                        },
                        new
                        {
                            Id = new Guid("0a20441e-d50a-4da4-b560-a91c4aa69080"),
                            Title = "BookChef"
                        },
                        new
                        {
                            Id = new Guid("07a4509b-9e0d-4cff-9ebb-8a7936f2dc4a"),
                            Title = "КСД"
                        });
                });

            modelBuilder.Entity("FindlyDAL.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceNodePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ba191c76-2816-43a1-94f1-45f2f9769a70"),
                            Name = "Yakaboo.ua",
                            ParserType = "JsonLd",
                            PriceNodePath = "//script[@data-vmid=\"ProductJsonLd\"]",
                            ShopImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("d63a589d-82e7-4dff-914e-7c64baefb06d"),
                            Name = "balka-book.com",
                            ParserType = "JsonLd",
                            PriceNodePath = "//script[@type='application/ld+json']",
                            ShopImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("8ab36ada-201e-4d5d-8ac5-2654e6569c64"),
                            Name = "book24.ua",
                            ParserType = "Node",
                            PriceNodePath = "//div[@class='product-main']//span[@class='price_value']",
                            ShopImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("ff6e7610-55b3-41f3-9b90-a375394cbe95"),
                            Name = "ksd.ua",
                            ParserType = "JsonLd",
                            PriceNodePath = "//script[@type='application/ld+json']",
                            ShopImageUrl = ""
                        });
                });

            modelBuilder.Entity("FindlyDAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FindlyDAL.Entities.UserLikedOffers", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PriceToNotify")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId", "OfferId");

                    b.HasIndex("OfferId");

                    b.ToTable("UserLikedOffers");
                });

            modelBuilder.Entity("authors_books", b =>
                {
                    b.Property<Guid>("authorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("bookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("authorId", "bookId");

                    b.HasIndex("bookId");

                    b.ToTable("authors_books");

                    b.HasData(
                        new
                        {
                            authorId = new Guid("a259a396-b950-4d63-8ce9-8b83fa187a8e"),
                            bookId = new Guid("26e5c51c-37e3-4c38-8e3e-41332eeaea73")
                        },
                        new
                        {
                            authorId = new Guid("a259a396-b950-4d63-8ce9-8b83fa187a8e"),
                            bookId = new Guid("00461873-724c-49bf-adde-fe204bce4466")
                        },
                        new
                        {
                            authorId = new Guid("391d1568-480f-4164-a10f-2c38a7391858"),
                            bookId = new Guid("11226951-89aa-4611-9346-11b9aba3d52d")
                        },
                        new
                        {
                            authorId = new Guid("7c69abe6-7604-4804-8d45-d5bdde4410d9"),
                            bookId = new Guid("c043abf2-91e1-4e68-82bd-8d55c88d7457")
                        });
                });

            modelBuilder.Entity("FindlyDAL.Entities.Book", b =>
                {
                    b.HasOne("FindlyDAL.Entities.Cover", "Cover")
                        .WithMany("Books")
                        .HasForeignKey("CoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cover");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Offer", b =>
                {
                    b.HasOne("FindlyDAL.Entities.Book", "Book")
                        .WithMany("Offers")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.Shop", "Shop")
                        .WithMany("Offers")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FindlyDAL.Entities.UserLikedOffers", b =>
                {
                    b.HasOne("FindlyDAL.Entities.Offer", "Offer")
                        .WithMany("LikedOffers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.User", "User")
                        .WithMany("LikedOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("authors_books", b =>
                {
                    b.HasOne("FindlyDAL.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("authorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FindlyDAL.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("bookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FindlyDAL.Entities.Book", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Cover", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Offer", b =>
                {
                    b.Navigation("LikedOffers");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FindlyDAL.Entities.Shop", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("FindlyDAL.Entities.User", b =>
                {
                    b.Navigation("LikedOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
